### ISSUE TITLE
Close popup button text not centered

### ISSUE THREAD

**Issue by Mego** [The-Quill/PopcornSE#4]
![image](https://cloud.githubusercontent.com/assets/853264/16941708/67f1a984-4d57-11e6-8240-957a56d2179d.png)

Either the button needs to be wider, or the text needs to be shorter.

**Comment by malachi26** [comment]
This should be fairly easy to fix.  I might be able to work on it later.

**Comment by malachi26** [comment]
What browser are you using?  I don't see this issue with Chrome `Version 51.0.2704.103 m`
