### ISSUE TITLE
Too many flags cause new flags to be hidden

### ISSUE THREAD

**Issue by Mego** [The-Quill/PopcornSE#5]
For example, with 11 flags recorded:

![image](https://cloud.githubusercontent.com/assets/853264/17097349/0e0a5544-5223-11e6-8558-c02c77942e27.png)

A scrollbar would help lots.

**Comment by The-Quill** [comment]
I literally copied the HTML structure from the upload box, which is too small to need scrolling, so it didn't have scrolling.... I might have to restructure how the layout's `position` rule is

**Comment by Mego** [comment]
Fixed in #6
